### ISSUE TITLE
 make develop command raises django-reversion dependency conflict issue 

### ISSUE THREAD

**Issue by Dev-Ahlam** [openwisp/docker-openwisp#358] opened 2024-09-11 06:46 UTC
**Describe the bug**
 whenever I run **make develop** command to build the images and use the new custom OPENWISP_UTILS I'm getting this issue

```
ERROR: Cannot install openwisp-controller and openwisp-controller==1.1a0 because these package versions have conflicting dependencies.

The conflict is caused by:
    openwisp-controller 1.1a0 depends on django-reversion~=5.0.12
    openwisp-ipam 1.1a0 depends on django-reversion~=5.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

**Steps To Reproduce**
I wanted to supply custom python code for openwisp-utils
I've created .build.env file in the root of the repository and added OPENWISP_UTILS_SOURCE variable and value
running make develop command raises the issue 

**Expected behavior**
the images should be built successfully 

**Screenshots**
![image](https://github.com/user-attachments/assets/b52d17e3-4d54-4f3a-b79e-a3a7a816a249)

**System Informatioon:**
 - OS: Ubuntu 20
 - Docker version: Docker version 24.0.1, build 6802122

**Comment by nemesifier** [comment] 2024-09-11 12:45
We are working to update the dependencies in preparation for the new release. We'll fix it asap.

**Comment by nemesifier** [comment] 2024-09-11 13:21
I couldn't reproduce the issue on the latest master, the instructions provided in "Steps To Reproduce" are not clear.
Hence I am closing this.

If you can provide clear step by step instructions that allow us to reproduce the issue on the latest master we can reopen.

Thanks for your understanding :pray:.

**Closed by nemesifier** 2024-09-11 13:21 UTC
Labels: bug
