### ISSUE TITLE
[error] host not found in upstream "radius" in /etc/nginx/conf.d/radius.https.conf

### ISSUE THREAD

**Issue by eltionb** [openwisp/docker-openwisp#248] opened 2022-07-12 19:20 UTC
Hello

I am getting this error on nginx container after a fresh install.
 Installed using auto-install.sh
_[emerg] 39#39: host not found in upstream "radius" in /etc/nginx/conf.d/radius.https.conf:71_

I did inspect docker file but cant find radius specified as a hostname anywhere. Anyone else has any idea?

OS: Ubuntu Server 20.04.4

**Comment by nemesisdesign** [comment] 2022-07-13 14:49
@eltionb try again with the edge images here: https://gitlab.com/openwisp/docker-openwisp/container_registry

**Comment by systemcrash** [comment] 2022-12-13 00:47
Would be great to get this into 'latest', ...

**Comment by benedikt-bartscher** [comment] 2023-01-11 23:59
same error here, even with edge images

**Comment by jrventer** [comment] 2023-01-19 05:11
It looks like the nginx is trying to connect with the API service with radius as a host. Likely some default setting that could be updated or aligned.

I worked around it by adding a alias to the API service in the docker-compose.yml
  api:
    image: openwisp/openwisp-api:latest
    restart: always
    build:
      context: images
      dockerfile: openwisp_api/Dockerfile
      args:
        API_APP_PORT: 8001
    env_file:
      - .env
    networks:
      default:
        aliases:
          - radius
    volumes:
      - influxdb_data:/var/lib/influxdb
      - openwisp_media:/opt/openwisp/media
      - ./customization/configuration/django/:/opt/openwisp/openwisp/configuration:ro
    depends_on:
      - postgres
      - redis
      - dashboard

**Comment by fuomag9** [comment] 2023-06-16 17:57
The issue is still present

**Comment by nemesifier** [comment] 2023-07-20 16:18
I cannot replicate this issue nor find anywhere in the code where radius.https.conf is created, this was an old file.

If anyone finds it in the code please send a patch.

Here's all the occurrences of the word "radius" in the actual codebase: https://github.com/search?q=repo%3Aopenwisp%2Fdocker-openwisp%20radius&type=code

**Comment by doreks** [comment] 2023-07-20 16:28
same issue here.  I added into .env file line NGINX_SERVER_NAME_HASH_BUCKET=64 but the error did not desappear

**Comment by doreks** [comment] 2023-07-20 17:16
hi, !

i have fixed the issue deploying **edge** docker
https://groups.google.com/g/openwisp/c/s4XQ2IOdUTk?pli=1

**Comment by focher** [comment] 2023-09-30 01:35
I have deployed using the edge version and still see this error. As the container keeps restarting due to the error, it's not even possible to connect to the container and diagnose the issue. Anyone have ideas?

**Comment by focher** [comment] 2024-02-12 18:18
Just posting back that I did resolve the error by changing the reference in the docker-compose.yml file from "freeradius" to "radius". It looks like that error message is just being unable to resolve "radius" to the running container.

**Comment by nemesifier** [comment] 2024-07-22 16:44
Should be fixed on the latest master, feel free to reopen if that's not the case.

**Closed by nemesifier** 2024-07-22 16:44 UTC
