### ISSUE TITLE
Link shortner (bit.do) is not responding

### ISSUE THREAD

**Issue by xewonder** [openwisp/docker-openwisp#265] opened 2023-02-15 12:11 UTC
Hello,

is this project still alive?

https://bit.do/auto-install is dead

**Comment by nemesisdesign** [comment] 2023-02-15 17:28
Yes it's alive and as indicated in the docs users are advised to be ready to get their hands dirty if they want to make it work.

![Screenshot from 2023-02-15 14-27-18](https://user-images.githubusercontent.com/841044/219106489-6697f8fc-d5a1-4e85-b250-d4d11dd50dd7.png)

If you want to open an issue please be more specific in explaining steps to reproduce it.

**Comment by xewonder** [comment] 2023-02-15 17:38
we are all ready to get our hands dirty, but when it fails at the first step:

   curl -L https://bit.do/auto-install -o setup.sh

you just have to ask yourself if the project is alive...

want me to be more specific?

https://bit.do/auto-install is dead!!!

**Comment by atb00ker** [comment] 2023-02-15 19:34
Hi @xewonder,

It looks like the redirecting url shortener service I was using is down.

Thanks for reporting that. 
I will change the title of the issue to reflect the problem with the link shortener.

Alternate link for the script can be used: 
https://raw.githubusercontent.com/openwisp/docker-openwisp/master/deploy/auto-install.sh

However, that said, you may face issues with that as well, as I have not used it for a while and cannot guarantee if it will be a one-click solution.

Please remember, docker-openwisp is in beta only.
Official installation method remains to be: https://github.com/openwisp/ansible-openwisp2

**Comment by nemesisdesign** [comment] 2023-02-15 19:41
Using a URL shortener was really a bad call.

**Comment by nemesisdesign** [comment] 2023-02-15 19:45
BTW @xewonder being more specific means writing "this URL X which is pointed out in the README is not reachable", writing "is dead" is not helpful because there's some maintainers which will not remember all the details of each repository from the top of their mind. So please be more specific next time to help maintainers understand the issue you're opening is valid.

**Comment by xewonder** [comment] 2023-02-15 20:53
yes, I agree and apologize for the wrong title... 

I have been "bitten" several times... wasting hours of my life just to realize the the project was dropped... 

Just happy that the project is ALIVE!

thank you for all the good work and i hope to be able to contribute..

**Comment by atb00ker** [comment] 2023-02-15 20:56
Please don't close it, I still need to update the link in the documentation! 😄

**Comment by xewonder** [comment] 2023-02-15 20:56
sorry...

**Comment by xewonder** [comment] 2023-02-17 09:21
nice that you added a label...

1> not changed
2> even with https://raw.githubusercontent.com/openwisp/docker-openwisp/master/deploy/auto-install.sh NGINX will not start on a vanilla ubuntu20.04

3> https://github.com/openwisp/ansible-openwisp2 following every instruction does not work on ubuntu 20.04

please change the title to DEAD because it is.. stop wasting our time!

**Comment by xewonder** [comment] 2023-02-17 09:25
..and @nemesisdesign  ... don't come with an attitude (AS I SEE YOU DO)... i have tried everything for the last 36 hours! step by step...

**Comment by xewonder** [comment] 2023-02-17 11:51
CIRCO AMERICANO!

latest.. .no nginx..

edge.. 502 Bad Gateway

FFS! some people are trying to work with you!

**Comment by nemesisdesign** [comment] 2023-02-17 13:06
Locked due to disrespectful behavior. https://openwisp.io/docs/general/code-of-conduct.html

**Comment by nemesisdesign** [comment] 2023-02-17 13:57
I have created a new issue without the drama: https://github.com/openwisp/docker-openwisp/issues/267.
This one will be deleted. Throwing tantrums and calling us names is not cool and will not be tolerated.

**Closed by nemesisdesign** 2023-02-17 13:57 UTC
Labels: good first issue
