### ISSUE TITLE
Services are not exposing ports on docker

### ISSUE THREAD

**Issue by yasir2000** [openwisp/docker-openwisp#290] opened 2023-10-22 10:57 UTC
After successful installation and all containers spawn on fresh ubuntu host as shown in Portainer, no exposed ports on dashboard and nginx service, despite no conflicting ports are there.

nginx container keeps restarting with log:

` host not found in upstream "radius" in /etc/nginx/conf.d/radius.https.conf:71
`
![image](https://github.com/openwisp/docker-openwisp/assets/6499373/4f0715b2-4712-4a1c-a2fd-0c045025b35e)

**Comment by macauleycheng** [comment] 2024-04-30 06:18
add this host "radius" into you /etc/hosts can solve this problem.
The problem is nginx can't find this "radius" host.

**Comment by nemesifier** [comment] 2024-05-01 21:35
Building the images from the master branch should fix this issue.

**Comment by nemesifier** [comment] 2024-07-22 16:37
Should be fixed on latest master, please reopen if that's not the case.

**Closed by nemesifier** 2024-07-22 16:37 UTC
